services:
  backend:
    build: .
    container_name: dictionary_api
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - USERNAME=root
      - PASSWORD=mysql
      - HOSTNAME=mysql
      - PORT=3306
      - DATABASE=dictionary-api
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dictionary_network
  
  database:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=dictionary-api
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - dictionary_network

networks:
  dictionary_network:
    driver: bridge